### ISSUE TITLE
Where does a TodoList actually get created?

### ISSUE THREAD

**Issue by ZempTime** [kickstarter/event-sourcing-rails-todo-app-demo#1]
Sorry if I missed it. By the time a `Events::TodoList::Created` gets applied to it's aggregate, that aggregate already exists?

Is it sorta pre-created in the controller, or does the event produce the creation of the aggregate?

**Comment by pcreux** [comment]
Hey @ZempTime, sorry, I missed your comment. The event produces the creation of the aggregate.

https://github.com/kickstarter/event-sourcing-rails-todo-app-demo/blob/7e14e0423af9848ff9bfa21677628515a25822bd/app/models/lib/base_event.rb#L82-L85
